package com.example.product.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class SecondStoreAuthentication implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store_authentication.id
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store_authentication.user_id
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store_authentication.name
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store_authentication.sex
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store_authentication.authentication_state
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    private Integer authenticationState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store_authentication.authentication_desc
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    private String authenticationDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store_authentication.create_date
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store_authentication.modify_date
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store_authentication.is_deleted
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table second_store_authentication
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store_authentication.id
     *
     * @return the value of second_store_authentication.id
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store_authentication.id
     *
     * @param id the value for second_store_authentication.id
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store_authentication.user_id
     *
     * @return the value of second_store_authentication.user_id
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store_authentication.user_id
     *
     * @param userId the value for second_store_authentication.user_id
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store_authentication.name
     *
     * @return the value of second_store_authentication.name
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store_authentication.name
     *
     * @param name the value for second_store_authentication.name
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store_authentication.sex
     *
     * @return the value of second_store_authentication.sex
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store_authentication.sex
     *
     * @param sex the value for second_store_authentication.sex
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store_authentication.authentication_state
     *
     * @return the value of second_store_authentication.authentication_state
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public Integer getAuthenticationState() {
        return authenticationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store_authentication.authentication_state
     *
     * @param authenticationState the value for second_store_authentication.authentication_state
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public void setAuthenticationState(Integer authenticationState) {
        this.authenticationState = authenticationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store_authentication.authentication_desc
     *
     * @return the value of second_store_authentication.authentication_desc
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public String getAuthenticationDesc() {
        return authenticationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store_authentication.authentication_desc
     *
     * @param authenticationDesc the value for second_store_authentication.authentication_desc
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public void setAuthenticationDesc(String authenticationDesc) {
        this.authenticationDesc = authenticationDesc == null ? null : authenticationDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store_authentication.create_date
     *
     * @return the value of second_store_authentication.create_date
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store_authentication.create_date
     *
     * @param createDate the value for second_store_authentication.create_date
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store_authentication.modify_date
     *
     * @return the value of second_store_authentication.modify_date
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store_authentication.modify_date
     *
     * @param modifyDate the value for second_store_authentication.modify_date
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store_authentication.is_deleted
     *
     * @return the value of second_store_authentication.is_deleted
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store_authentication.is_deleted
     *
     * @param isDeleted the value for second_store_authentication.is_deleted
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_store_authentication
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", authenticationState=").append(authenticationState);
        sb.append(", authenticationDesc=").append(authenticationDesc);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}