package com.example.product.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class SecondProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.id
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.product_type
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private String productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.show_type
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private String showType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.product_name
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.category_id
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.file
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private String file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.address_id
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.store_id
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.is_putaway
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private Integer isPutaway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.product_state
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private String productState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.create_time
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.modify_time
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.is_deleted
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private Short isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_product.product_desc
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table second_product
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.id
     *
     * @return the value of second_product.id
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.id
     *
     * @param id the value for second_product.id
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.product_type
     *
     * @return the value of second_product.product_type
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.product_type
     *
     * @param productType the value for second_product.product_type
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setProductType(String productType) {
        this.productType = productType == null ? null : productType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.show_type
     *
     * @return the value of second_product.show_type
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public String getShowType() {
        return showType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.show_type
     *
     * @param showType the value for second_product.show_type
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setShowType(String showType) {
        this.showType = showType == null ? null : showType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.product_name
     *
     * @return the value of second_product.product_name
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.product_name
     *
     * @param productName the value for second_product.product_name
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.category_id
     *
     * @return the value of second_product.category_id
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.category_id
     *
     * @param categoryId the value for second_product.category_id
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.file
     *
     * @return the value of second_product.file
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.file
     *
     * @param file the value for second_product.file
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.address_id
     *
     * @return the value of second_product.address_id
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.address_id
     *
     * @param addressId the value for second_product.address_id
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.store_id
     *
     * @return the value of second_product.store_id
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.store_id
     *
     * @param storeId the value for second_product.store_id
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.is_putaway
     *
     * @return the value of second_product.is_putaway
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public Integer getIsPutaway() {
        return isPutaway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.is_putaway
     *
     * @param isPutaway the value for second_product.is_putaway
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setIsPutaway(Integer isPutaway) {
        this.isPutaway = isPutaway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.product_state
     *
     * @return the value of second_product.product_state
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public String getProductState() {
        return productState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.product_state
     *
     * @param productState the value for second_product.product_state
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setProductState(String productState) {
        this.productState = productState == null ? null : productState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.create_time
     *
     * @return the value of second_product.create_time
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.create_time
     *
     * @param createTime the value for second_product.create_time
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.modify_time
     *
     * @return the value of second_product.modify_time
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.modify_time
     *
     * @param modifyTime the value for second_product.modify_time
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.is_deleted
     *
     * @return the value of second_product.is_deleted
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.is_deleted
     *
     * @param isDeleted the value for second_product.is_deleted
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_product.product_desc
     *
     * @return the value of second_product.product_desc
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_product.product_desc
     *
     * @param productDesc the value for second_product.product_desc
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_product
     *
     * @mbg.generated Sun Oct 11 09:21:43 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productType=").append(productType);
        sb.append(", showType=").append(showType);
        sb.append(", productName=").append(productName);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", file=").append(file);
        sb.append(", addressId=").append(addressId);
        sb.append(", storeId=").append(storeId);
        sb.append(", isPutaway=").append(isPutaway);
        sb.append(", productState=").append(productState);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", productDesc=").append(productDesc);
        sb.append("]");
        return sb.toString();
    }
}