package com.example.product.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class SecondCategory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_category.id
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_category.second_name
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    private String secondName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_category.parent_category_id
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    private Integer parentCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_category.level_id
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    private Integer levelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_category.file
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    private String file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_category.create_time
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_category.modify_time
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_category.is_deleted
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    private Short isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table second_category
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_category.id
     *
     * @return the value of second_category.id
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_category.id
     *
     * @param id the value for second_category.id
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_category.second_name
     *
     * @return the value of second_category.second_name
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public String getSecondName() {
        return secondName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_category.second_name
     *
     * @param secondName the value for second_category.second_name
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public void setSecondName(String secondName) {
        this.secondName = secondName == null ? null : secondName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_category.parent_category_id
     *
     * @return the value of second_category.parent_category_id
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public Integer getParentCategoryId() {
        return parentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_category.parent_category_id
     *
     * @param parentCategoryId the value for second_category.parent_category_id
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public void setParentCategoryId(Integer parentCategoryId) {
        this.parentCategoryId = parentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_category.level_id
     *
     * @return the value of second_category.level_id
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_category.level_id
     *
     * @param levelId the value for second_category.level_id
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_category.file
     *
     * @return the value of second_category.file
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_category.file
     *
     * @param file the value for second_category.file
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_category.create_time
     *
     * @return the value of second_category.create_time
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_category.create_time
     *
     * @param createTime the value for second_category.create_time
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_category.modify_time
     *
     * @return the value of second_category.modify_time
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_category.modify_time
     *
     * @param modifyTime the value for second_category.modify_time
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_category.is_deleted
     *
     * @return the value of second_category.is_deleted
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_category.is_deleted
     *
     * @param isDeleted the value for second_category.is_deleted
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_category
     *
     * @mbg.generated Mon Sep 14 14:07:18 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", secondName=").append(secondName);
        sb.append(", parentCategoryId=").append(parentCategoryId);
        sb.append(", levelId=").append(levelId);
        sb.append(", file=").append(file);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}