package com.example.product.center.dao;

import com.example.product.center.model.SecondStoreAuthentication;
import com.example.product.center.model.SecondStoreAuthenticationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondStoreAuthenticationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_store_authentication
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    long countByExample(SecondStoreAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_store_authentication
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    int deleteByExample(SecondStoreAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_store_authentication
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_store_authentication
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    int insert(SecondStoreAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_store_authentication
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    int insertSelective(SecondStoreAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_store_authentication
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    List<SecondStoreAuthentication> selectByExample(SecondStoreAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_store_authentication
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    SecondStoreAuthentication selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_store_authentication
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecondStoreAuthentication record, @Param("example") SecondStoreAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_store_authentication
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    int updateByExample(@Param("record") SecondStoreAuthentication record, @Param("example") SecondStoreAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_store_authentication
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    int updateByPrimaryKeySelective(SecondStoreAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_store_authentication
     *
     * @mbg.generated Thu Sep 10 17:38:15 CST 2020
     */
    int updateByPrimaryKey(SecondStoreAuthentication record);
}