package com.example.product.center.dao;

import com.example.product.center.model.SecondUserAddress;
import com.example.product.center.model.SecondUserAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondUserAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_address
     *
     * @mbg.generated Wed Sep 09 09:12:19 CST 2020
     */
    long countByExample(SecondUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_address
     *
     * @mbg.generated Wed Sep 09 09:12:19 CST 2020
     */
    int deleteByExample(SecondUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_address
     *
     * @mbg.generated Wed Sep 09 09:12:19 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_address
     *
     * @mbg.generated Wed Sep 09 09:12:19 CST 2020
     */
    int insert(SecondUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_address
     *
     * @mbg.generated Wed Sep 09 09:12:19 CST 2020
     */
    int insertSelective(SecondUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_address
     *
     * @mbg.generated Wed Sep 09 09:12:19 CST 2020
     */
    List<SecondUserAddress> selectByExample(SecondUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_address
     *
     * @mbg.generated Wed Sep 09 09:12:19 CST 2020
     */
    SecondUserAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_address
     *
     * @mbg.generated Wed Sep 09 09:12:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecondUserAddress record, @Param("example") SecondUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_address
     *
     * @mbg.generated Wed Sep 09 09:12:19 CST 2020
     */
    int updateByExample(@Param("record") SecondUserAddress record, @Param("example") SecondUserAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_address
     *
     * @mbg.generated Wed Sep 09 09:12:19 CST 2020
     */
    int updateByPrimaryKeySelective(SecondUserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_address
     *
     * @mbg.generated Wed Sep 09 09:12:19 CST 2020
     */
    int updateByPrimaryKey(SecondUserAddress record);
}