package com.example.product.center.dao;

import com.example.product.center.model.SecondUserSon;
import com.example.product.center.model.SecondUserSonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondUserSonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_son
     *
     * @mbg.generated Fri Sep 18 10:45:05 CST 2020
     */
    long countByExample(SecondUserSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_son
     *
     * @mbg.generated Fri Sep 18 10:45:05 CST 2020
     */
    int deleteByExample(SecondUserSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_son
     *
     * @mbg.generated Fri Sep 18 10:45:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_son
     *
     * @mbg.generated Fri Sep 18 10:45:05 CST 2020
     */
    int insert(SecondUserSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_son
     *
     * @mbg.generated Fri Sep 18 10:45:05 CST 2020
     */
    int insertSelective(SecondUserSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_son
     *
     * @mbg.generated Fri Sep 18 10:45:05 CST 2020
     */
    List<SecondUserSon> selectByExample(SecondUserSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_son
     *
     * @mbg.generated Fri Sep 18 10:45:05 CST 2020
     */
    SecondUserSon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_son
     *
     * @mbg.generated Fri Sep 18 10:45:05 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecondUserSon record, @Param("example") SecondUserSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_son
     *
     * @mbg.generated Fri Sep 18 10:45:05 CST 2020
     */
    int updateByExample(@Param("record") SecondUserSon record, @Param("example") SecondUserSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_son
     *
     * @mbg.generated Fri Sep 18 10:45:05 CST 2020
     */
    int updateByPrimaryKeySelective(SecondUserSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_user_son
     *
     * @mbg.generated Fri Sep 18 10:45:05 CST 2020
     */
    int updateByPrimaryKey(SecondUserSon record);
}