package com.example.user.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class SecondChat implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_chat.id
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_chat.to_id
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    private Integer toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_chat.from_id
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    private Integer fromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_chat.send_time
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    private LocalDateTime sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_chat.type
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_chat.read_status
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    private Byte readStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_chat.create_time
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_chat.modify_time
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_chat.is_deleted
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_chat.content
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table second_chat
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_chat.id
     *
     * @return the value of second_chat.id
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_chat.id
     *
     * @param id the value for second_chat.id
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_chat.to_id
     *
     * @return the value of second_chat.to_id
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_chat.to_id
     *
     * @param toId the value for second_chat.to_id
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_chat.from_id
     *
     * @return the value of second_chat.from_id
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_chat.from_id
     *
     * @param fromId the value for second_chat.from_id
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_chat.send_time
     *
     * @return the value of second_chat.send_time
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public LocalDateTime getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_chat.send_time
     *
     * @param sendTime the value for second_chat.send_time
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public void setSendTime(LocalDateTime sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_chat.type
     *
     * @return the value of second_chat.type
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_chat.type
     *
     * @param type the value for second_chat.type
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_chat.read_status
     *
     * @return the value of second_chat.read_status
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public Byte getReadStatus() {
        return readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_chat.read_status
     *
     * @param readStatus the value for second_chat.read_status
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public void setReadStatus(Byte readStatus) {
        this.readStatus = readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_chat.create_time
     *
     * @return the value of second_chat.create_time
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_chat.create_time
     *
     * @param createTime the value for second_chat.create_time
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_chat.modify_time
     *
     * @return the value of second_chat.modify_time
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_chat.modify_time
     *
     * @param modifyTime the value for second_chat.modify_time
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_chat.is_deleted
     *
     * @return the value of second_chat.is_deleted
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_chat.is_deleted
     *
     * @param isDeleted the value for second_chat.is_deleted
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_chat.content
     *
     * @return the value of second_chat.content
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_chat.content
     *
     * @param content the value for second_chat.content
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_chat
     *
     * @mbg.generated Mon Sep 28 14:26:56 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", toId=").append(toId);
        sb.append(", fromId=").append(fromId);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", type=").append(type);
        sb.append(", readStatus=").append(readStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }
}