package com.example.order.center.dao;

import com.example.order.center.model.SecondWithdrawalAudit;
import com.example.order.center.model.SecondWithdrawalAuditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondWithdrawalAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_withdrawal_audit
     *
     * @mbg.generated Fri Sep 11 16:22:40 CST 2020
     */
    long countByExample(SecondWithdrawalAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_withdrawal_audit
     *
     * @mbg.generated Fri Sep 11 16:22:40 CST 2020
     */
    int deleteByExample(SecondWithdrawalAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_withdrawal_audit
     *
     * @mbg.generated Fri Sep 11 16:22:40 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_withdrawal_audit
     *
     * @mbg.generated Fri Sep 11 16:22:40 CST 2020
     */
    int insert(SecondWithdrawalAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_withdrawal_audit
     *
     * @mbg.generated Fri Sep 11 16:22:40 CST 2020
     */
    int insertSelective(SecondWithdrawalAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_withdrawal_audit
     *
     * @mbg.generated Fri Sep 11 16:22:40 CST 2020
     */
    List<SecondWithdrawalAudit> selectByExample(SecondWithdrawalAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_withdrawal_audit
     *
     * @mbg.generated Fri Sep 11 16:22:40 CST 2020
     */
    SecondWithdrawalAudit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_withdrawal_audit
     *
     * @mbg.generated Fri Sep 11 16:22:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecondWithdrawalAudit record, @Param("example") SecondWithdrawalAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_withdrawal_audit
     *
     * @mbg.generated Fri Sep 11 16:22:40 CST 2020
     */
    int updateByExample(@Param("record") SecondWithdrawalAudit record, @Param("example") SecondWithdrawalAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_withdrawal_audit
     *
     * @mbg.generated Fri Sep 11 16:22:40 CST 2020
     */
    int updateByPrimaryKeySelective(SecondWithdrawalAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_withdrawal_audit
     *
     * @mbg.generated Fri Sep 11 16:22:40 CST 2020
     */
    int updateByPrimaryKey(SecondWithdrawalAudit record);
}