package com.example.payment.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class SecondStore implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.id
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.store_type
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private String storeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.store_name
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.user_id
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.second_desc
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private String secondDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.boss_id
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private Integer bossId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.second_balance
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private Integer secondBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.create_time
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.expire_time
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private LocalDateTime expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.modify_date
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.second_status
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private Integer secondStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.is_deleted
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private Short isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.concern_count
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private Integer concernCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column second_store.second_address
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private String secondAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table second_store
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.id
     *
     * @return the value of second_store.id
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.id
     *
     * @param id the value for second_store.id
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.store_type
     *
     * @return the value of second_store.store_type
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public String getStoreType() {
        return storeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.store_type
     *
     * @param storeType the value for second_store.store_type
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setStoreType(String storeType) {
        this.storeType = storeType == null ? null : storeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.store_name
     *
     * @return the value of second_store.store_name
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.store_name
     *
     * @param storeName the value for second_store.store_name
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.user_id
     *
     * @return the value of second_store.user_id
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.user_id
     *
     * @param userId the value for second_store.user_id
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.second_desc
     *
     * @return the value of second_store.second_desc
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public String getSecondDesc() {
        return secondDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.second_desc
     *
     * @param secondDesc the value for second_store.second_desc
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setSecondDesc(String secondDesc) {
        this.secondDesc = secondDesc == null ? null : secondDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.boss_id
     *
     * @return the value of second_store.boss_id
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public Integer getBossId() {
        return bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.boss_id
     *
     * @param bossId the value for second_store.boss_id
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setBossId(Integer bossId) {
        this.bossId = bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.second_balance
     *
     * @return the value of second_store.second_balance
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public Integer getSecondBalance() {
        return secondBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.second_balance
     *
     * @param secondBalance the value for second_store.second_balance
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setSecondBalance(Integer secondBalance) {
        this.secondBalance = secondBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.create_time
     *
     * @return the value of second_store.create_time
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.create_time
     *
     * @param createTime the value for second_store.create_time
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.expire_time
     *
     * @return the value of second_store.expire_time
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public LocalDateTime getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.expire_time
     *
     * @param expireTime the value for second_store.expire_time
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setExpireTime(LocalDateTime expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.modify_date
     *
     * @return the value of second_store.modify_date
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.modify_date
     *
     * @param modifyDate the value for second_store.modify_date
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.second_status
     *
     * @return the value of second_store.second_status
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public Integer getSecondStatus() {
        return secondStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.second_status
     *
     * @param secondStatus the value for second_store.second_status
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setSecondStatus(Integer secondStatus) {
        this.secondStatus = secondStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.is_deleted
     *
     * @return the value of second_store.is_deleted
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.is_deleted
     *
     * @param isDeleted the value for second_store.is_deleted
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.concern_count
     *
     * @return the value of second_store.concern_count
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public Integer getConcernCount() {
        return concernCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.concern_count
     *
     * @param concernCount the value for second_store.concern_count
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setConcernCount(Integer concernCount) {
        this.concernCount = concernCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column second_store.second_address
     *
     * @return the value of second_store.second_address
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public String getSecondAddress() {
        return secondAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column second_store.second_address
     *
     * @param secondAddress the value for second_store.second_address
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    public void setSecondAddress(String secondAddress) {
        this.secondAddress = secondAddress == null ? null : secondAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_store
     *
     * @mbg.generated Wed Sep 09 15:47:52 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", storeType=").append(storeType);
        sb.append(", storeName=").append(storeName);
        sb.append(", userId=").append(userId);
        sb.append(", secondDesc=").append(secondDesc);
        sb.append(", bossId=").append(bossId);
        sb.append(", secondBalance=").append(secondBalance);
        sb.append(", createTime=").append(createTime);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", secondStatus=").append(secondStatus);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", concernCount=").append(concernCount);
        sb.append(", secondAddress=").append(secondAddress);
        sb.append("]");
        return sb.toString();
    }
}