package com.example.user.center.dao;

import com.example.user.center.model.SecondSon;
import com.example.user.center.model.SecondSonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondSonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_son
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    long countByExample(SecondSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_son
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int deleteByExample(SecondSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_son
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_son
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int insert(SecondSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_son
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int insertSelective(SecondSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_son
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    List<SecondSon> selectByExample(SecondSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_son
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    SecondSon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_son
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecondSon record, @Param("example") SecondSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_son
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int updateByExample(@Param("record") SecondSon record, @Param("example") SecondSonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_son
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int updateByPrimaryKeySelective(SecondSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_son
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int updateByPrimaryKey(SecondSon record);
}