package com.example.user.center.dao;

import com.example.user.center.model.SecondGoodsSpec;
import com.example.user.center.model.SecondGoodsSpecExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondGoodsSpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_goods_spec
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    long countByExample(SecondGoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_goods_spec
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int deleteByExample(SecondGoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_goods_spec
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_goods_spec
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int insert(SecondGoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_goods_spec
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int insertSelective(SecondGoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_goods_spec
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    List<SecondGoodsSpec> selectByExample(SecondGoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_goods_spec
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    SecondGoodsSpec selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_goods_spec
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecondGoodsSpec record, @Param("example") SecondGoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_goods_spec
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int updateByExample(@Param("record") SecondGoodsSpec record, @Param("example") SecondGoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_goods_spec
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int updateByPrimaryKeySelective(SecondGoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_goods_spec
     *
     * @mbg.generated Fri Sep 11 11:15:05 CST 2020
     */
    int updateByPrimaryKey(SecondGoodsSpec record);
}