package com.example.user.center.dao;

import com.example.user.center.model.SecondBoss;
import com.example.user.center.model.SecondBossExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondBossMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    long countByExample(SecondBossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int deleteByExample(SecondBossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int insert(SecondBoss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int insertSelective(SecondBoss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    List<SecondBoss> selectByExampleWithBLOBs(SecondBossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    List<SecondBoss> selectByExample(SecondBossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    SecondBoss selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecondBoss record, @Param("example") SecondBossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") SecondBoss record, @Param("example") SecondBossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int updateByExample(@Param("record") SecondBoss record, @Param("example") SecondBossExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int updateByPrimaryKeySelective(SecondBoss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(SecondBoss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_boss
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int updateByPrimaryKey(SecondBoss record);
}