package com.example.user.center.dao;

import com.example.user.center.model.SecondSlideshow;
import com.example.user.center.model.SecondSlideshowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondSlideshowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_slideshow
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    long countByExample(SecondSlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_slideshow
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int deleteByExample(SecondSlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_slideshow
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_slideshow
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int insert(SecondSlideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_slideshow
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int insertSelective(SecondSlideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_slideshow
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    List<SecondSlideshow> selectByExample(SecondSlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_slideshow
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    SecondSlideshow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_slideshow
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecondSlideshow record, @Param("example") SecondSlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_slideshow
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int updateByExample(@Param("record") SecondSlideshow record, @Param("example") SecondSlideshowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_slideshow
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int updateByPrimaryKeySelective(SecondSlideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_slideshow
     *
     * @mbg.generated Fri Sep 11 17:49:54 CST 2020
     */
    int updateByPrimaryKey(SecondSlideshow record);
}