package com.example.user.center.dao;

import com.example.user.center.model.SecondProductAddress;
import com.example.user.center.model.SecondProductAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondProductAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_product_address
     *
     * @mbg.generated Mon Sep 14 12:09:37 CST 2020
     */
    long countByExample(SecondProductAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_product_address
     *
     * @mbg.generated Mon Sep 14 12:09:37 CST 2020
     */
    int deleteByExample(SecondProductAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_product_address
     *
     * @mbg.generated Mon Sep 14 12:09:37 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_product_address
     *
     * @mbg.generated Mon Sep 14 12:09:37 CST 2020
     */
    int insert(SecondProductAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_product_address
     *
     * @mbg.generated Mon Sep 14 12:09:37 CST 2020
     */
    int insertSelective(SecondProductAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_product_address
     *
     * @mbg.generated Mon Sep 14 12:09:37 CST 2020
     */
    List<SecondProductAddress> selectByExample(SecondProductAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_product_address
     *
     * @mbg.generated Mon Sep 14 12:09:37 CST 2020
     */
    SecondProductAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_product_address
     *
     * @mbg.generated Mon Sep 14 12:09:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecondProductAddress record, @Param("example") SecondProductAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_product_address
     *
     * @mbg.generated Mon Sep 14 12:09:37 CST 2020
     */
    int updateByExample(@Param("record") SecondProductAddress record, @Param("example") SecondProductAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_product_address
     *
     * @mbg.generated Mon Sep 14 12:09:37 CST 2020
     */
    int updateByPrimaryKeySelective(SecondProductAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_product_address
     *
     * @mbg.generated Mon Sep 14 12:09:37 CST 2020
     */
    int updateByPrimaryKey(SecondProductAddress record);
}