package com.example.payment.center.dao;

import com.example.payment.center.model.SecondOrderVideo;
import com.example.payment.center.model.SecondOrderVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecondOrderVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_order_video
     *
     * @mbg.generated Fri Dec 04 11:26:04 CST 2020
     */
    long countByExample(SecondOrderVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_order_video
     *
     * @mbg.generated Fri Dec 04 11:26:04 CST 2020
     */
    int deleteByExample(SecondOrderVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_order_video
     *
     * @mbg.generated Fri Dec 04 11:26:04 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_order_video
     *
     * @mbg.generated Fri Dec 04 11:26:04 CST 2020
     */
    int insert(SecondOrderVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_order_video
     *
     * @mbg.generated Fri Dec 04 11:26:04 CST 2020
     */
    int insertSelective(SecondOrderVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_order_video
     *
     * @mbg.generated Fri Dec 04 11:26:04 CST 2020
     */
    List<SecondOrderVideo> selectByExample(SecondOrderVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_order_video
     *
     * @mbg.generated Fri Dec 04 11:26:04 CST 2020
     */
    SecondOrderVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_order_video
     *
     * @mbg.generated Fri Dec 04 11:26:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") SecondOrderVideo record, @Param("example") SecondOrderVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_order_video
     *
     * @mbg.generated Fri Dec 04 11:26:04 CST 2020
     */
    int updateByExample(@Param("record") SecondOrderVideo record, @Param("example") SecondOrderVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_order_video
     *
     * @mbg.generated Fri Dec 04 11:26:04 CST 2020
     */
    int updateByPrimaryKeySelective(SecondOrderVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table second_order_video
     *
     * @mbg.generated Fri Dec 04 11:26:04 CST 2020
     */
    int updateByPrimaryKey(SecondOrderVideo record);
}