spring:
  application:
    name: product-server
  rabbitmq:
    host: 39.100.237.144
    port: 5672
    username: sw
    password: Davin1203!
  redis:
    database: 0
    host: 39.100.237.144
    port: 16379
    timeout: 10000ms
    jedis:
      pool:
        max-active: 16
        max-idle: 4
server:
  port: 7003
  servlet:
    context-path: /order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5060/eureka/eureka
